### ISSUE TITLE
ViewModel Property in Cell

### ISSUE THREAD

**Issue by rzee7** [XnainA/XamarinProfile#2]
@XnainA take a look:

_Note: See images for result and how to take steps_

1: [Step 1](http://screencast.com/t/ojw2rgkC80)
2: [Step 2](http://screencast.com/t/Uaoaq0a7xmz)
3: [Step 3](http://screencast.com/t/XGrjnmUfe)
4: [Step 4](http://screencast.com/t/STTJaQlF)

[WrapUserModel](http://pastebin.com/jN0qSTRy)
[UserViewModel Code](http://pastebin.com/Y9RWCqVY)
[CreateCellView()](http://pastebin.com/sJvguiZ2)
[UserListPage](http://pastebin.com/nJtegZ24)

Cheers!!

**Comment by NainaSharma190790** [comment]
Thank you so much :)

**Comment by rzee7** [comment]
@XnainA  Delete your comment or EDIT this, It shows your number  :)
